name: LibertyCity
version: '${project.version}'
main: com.xiii.libertycity.LibertyCity
authors: [ XIII___ ]
description: LibertyCity Plugin
commands:
  clearlag:
    description: LibertyCity's clearlag command.
    usage: /clearlag
    permission: LibertyCity.STAFF
  kick:
    description: LibertyCity's kick command.
    usage: /kick
    permission: LibertyCity.STAFF
  ping:
    description: LibertyCity's ping command.
    usage: /ping
    permission: LibertyCity.BASIC
  mutechat:
    description: LibertyCity's mutechat command.
    usage: /mutechat
    permission: LibertyCity.STAFF
  cooldownchat:
    description: LibertyCity's cooldownchat command.
    usage: /cooldownchat
    permission: LibertyCity.STAFF
  clearchat:
    description: LibertyCity's clearchat command.
    usage: /clearchat
    permission: LibertyCity.STAFF
  atm:
    description: LibertyCity's ATM command.
    usage: /atm
    permission: LibertyCity.DEBUG
  chat:
    description: LibertyCity's chat command.
    usage: /chat
    permission: LibertyCity.BASIC
  report:
    description: LibertyCity's report command.
    usage: /report
    permission: LibertyCity.BASIC
  unban:
    description: LibertyCity's unban command.
    usage: /unban
    permission: LibertyCity.STAFF
  spy:
    description: LibertyCity's spychat command.
    usage: /spy
    permission: LibertyCity.STAFF
  gm:
    description: LibertyCity's gamemode command.
    usage: /gm
    permission: LibertyCity.STAFF
  gamemode:
    description: LibertyCity's gamemode command.
    usage: /gamemode
    permission: LibertyCity.STAFF
  gms:
    description: LibertyCity's survival gamemode command.
    usage: /gms
    permission: LibertyCity.STAFF
  gma:
    description: LibertyCity's adventure gamemode command.
    usage: /gma
    permission: LibertyCity.STAFF
  gmc:
    description: LibertyCity's creative gamemode command.
    usage: /gmc
    permission: LibertyCity.STAFF
  gmsp:
    description: LibertyCity's spectator gamemode command.
    usage: /gmsp
    permission: LibertyCity.STAFF
  clear:
    description: LibertyCity's clear command.
    usage: /clear
    permission: LibertyCity.STAFF
  ci:
    description: LibertyCity's clear command.
    usage: /ci
    permission: LibertyCity.STAFF
  feed:
    description: LibertyCity's feed command.
    usage: /feed
    permission: LibertyCity.STAFF
  heal:
    description: LibertyCity's heal command.
    usage: /heal
    permission: LibertyCity.STAFF
  fly:
    description: LibertyCity's fly command.
    usage: /fly
    permission: LibertyCity.STAFF
  teleport:
    description: LibertyCity's teleport command.
    usage: /teleport
    permission: LibertyCity.STAFF
  tp:
    description: LibertyCity's teleport command.
    usage: /tp
    permission: LibertyCity.STAFF
  day:
    description: LibertyCity's day command.
    usage: /day
    permission: LibertyCity.STAFF
  night:
    description: LibertyCity's night command.
    usage: /night
    permission: LibertyCity.STAFF
  v:
    description: LibertyCity's v command.
    usage: /v
    permission: LibertyCity.STAFF
  vanish:
    description: LibertyCity's vanish command.
    usage: /vanish
    permission: LibertyCity.STAFF
