name: LibertyCity
version: '${project.version}'
main: com.xiii.libertycity.LibertyCity
authors: [ XIII___ ]
description: LibertyCity Plugin
commands:
  clearlag:
    description: LibertyCity's clearlag command.
    usage: /clearlag
    permission: LibertyCity.STAFF
  kick:
    description: LibertyCity's kick command.
    usage: /kick
    permission: LibertyCity.STAFF
  ping:
    description: LibertyCity's ping command.
    usage: /ping
    permission: LibertyCity.BASIC
  mutechat:
    description: LibertyCity's mutechat command.
    usage: /mutechat
    permission: LibertyCity.STAFF
  cooldownchat:
    description: LibertyCity's cooldownchat command.
    usage: /cooldownchat
    permission: LibertyCity.STAFF
  clearchat:
    description: LibertyCity's clearchat command.
    usage: /clearchat
    permission: LibertyCity.STAFF
  atm:
    description: LibertyCity's ATM command.
    usage: /atm
    permission: LibertyCity.DEBUG
  chat:
    description: LibertyCity's chat command.
    usage: /chat
    permission: LibertyCity.BASIC
  report:
    description: LibertyCity's report command.
    usage: /report
    permission: LibertyCity.BASIC
  unban:
    description: LibertyCity's unban command.
    usage: /unban
    permission: LibertyCity.STAFF
  spy:
    description: LibertyCity's spychat command.
    usage: /spy
    permission: LibertyCity.STAFF
